apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-flask
  template:
    metadata:
      labels:
        app: simple-flask
    spec:
      containers:
      - name: simple-flask-container
        image: massoft/simple-flask-cicd:latest
        ports:
        - containerPort: 5000
